#!/usr/bin/env python

import argparse
import glob

import numpy as np

from EffectiveTTVProduction.EffectiveTTVProduction.cross_sections import CrossSectionScan

parser = argparse.ArgumentParser(description='merge CrossSectionScan files')
parser.add_argument('outfile', help='name of output merged file')
parser.add_argument('infiles', nargs='+', help='files to merge (wildcards accepted)')
args = parser.parse_args()

files = []
for fn in args.infiles:
    files += glob.glob(fn.replace('file:', ''))

cross_section_scan = CrossSectionScan(files)
cross_section_scan.dump(args.outfile)
